''' Art styles are appended to the prompt with a lower weight. Experiment here and add your own! '''
styles = [
    "DeviantArt",
    "CryEngine",
    "National Geographic photo",
    "Pixar film",
    "Studio Ghibli",
    "hyperrealism",
    "psychedelic",
    "cyberpunk",
    "synthwave",
    "low poly",
    "drone view",
    "ultrafine detail",
    "chalk art",
    "child's drawing",
    "oil on canvas",
    "watercolor",
    "tempera painting"
    "stipple",
    "pencil sketch",
    "charcoal sketch",
    "ink drawing",
    "Albrecht Dürer",
    "Gustave Dore",
    "Pablo Picasso",
    "Feng Zhu",
    "Lisa Frank",
    "Trending on ArtStation"
]
